export const EMAIL = 'harikrish18342@gmail.com'
export const GITHUB = 'https://github.com/AMAZINGHARIKRISHNAN'
export const LINKEDIN = 'https://www.linkedin.com/in/hari-krishnan-p-1854a51b2/'
export const projects = [
  {
    id: 'regs-qa',
    title: 'Internal Regulations QA System',
    category: 'web',
    work: true,
    image: '/assets/images/projects/regs-qa.webp',
    desc: 'RAG-powered internal AI chatbot answering questions about company regulations, used across Thirdwave (Dec 2025).',
    tech: ['rag', 'llm', 'langchain'],
    github: '#',
    live: '#',
  },
  {
    id: 'filemgmt',
    title: 'File Management System (PoC)',
    category: 'web',
    work: true,
    image: '/assets/images/projects/filemgmt.webp',
    desc: 'Proof-of-concept file management system for internal operations — in active development (2026).',
    tech: ['web', 'poc'],
    github: '#',
    live: '#',
  },
  {
    id: 'eyenavi',
    title: 'Eye Navi (Android)',
    category: 'mobile',
    work: true,
    image: '/assets/images/projects/eyenavi.webp',
    desc: 'Android version of the "Eye Navi" walking-navigation iOS app, built on secondment at Computer Science Laboratory, Kitakyushu.',
    tech: ['android', 'navigation'],
    github: '#',
    live: '#',
  },
  {
    id: 'adminxpert',
    title: "The Nest's AdminXpert",
    category: 'web',
    image: '/assets/images/projects/adminxpert.webp',
    desc: 'Administrative management platform with custom workflows powering day-to-day school operations.',
    tech: ['react', 'firebase', 'css3'],
    github: '#',
    live: '#',
  },
  {
    id: 'examcell',
    title: 'MSEC ExamCell',
    category: 'web',
    image: '/assets/images/projects/examcell.webp',
    desc: 'Examination cell management system used by Meenakshi Sundararajan Engineering College.',
    tech: ['html5', 'css3', 'javascript', 'firebase'],
    github: '#',
    live: '#',
  },
  {
    id: 'empoweringvoters',
    title: 'EmpoweringVoters',
    category: 'web',
    image: '/assets/images/projects/empoweringvoters.webp',
    desc: 'Voter education and awareness platform with interactive learning features.',
    tech: ['react', 'node.js', 'mysql'],
    github: '#',
    live: '#',
  },
  {
    id: 'nestsecurity',
    title: 'TheNestSecurity',
    category: 'mobile',
    image: '/assets/images/projects/nestsecurity.webp',
    fit: 'contain',
    desc: 'Cross-platform security and monitoring app for The Nest School campus.',
    tech: ['flutter', 'firebase'],
    github: '#',
    live: '#',
  },
  {
    id: 'serviceregister',
    title: 'Service Register',
    category: 'web',
    image: '/assets/images/projects/serviceregister.webp',
    fit: 'contain',
    desc: 'Digital service registration and tracking system for operational management.',
    tech: ['html5', 'css3', 'javascript'],
    github: '#',
    live: '#',
  },
  {
    id: 'medscan',
    title: 'MedScan Master',
    category: 'web',
    image: '/assets/images/projects/medscan.webp',
    fit: 'contain',
    desc: 'Medical document scanning and intelligent management application.',
    tech: ['python', 'react', 'firebase'],
    github: '#',
    live: '#',
  },
]

export const experience = [
  {
    company: 'Thirdwave Corporation',
    role: 'AI Application Engineer · Digital Innovation Div. 3',
    place: 'Tokyo, Japan 🇯🇵',
    period: '2025 — present',
    current: true,
    points: [
      'Built the internal regulations Q&A system — a RAG-powered AI chatbot for company-wide use (Dec 2025).',
      'Developing a file management system PoC for internal operations (Jun 2026 — present).',
      'Seconded to Computer Science Laboratory (Kitakyushu) to build the Android version of the "Eye Navi" navigation app (Jul–Sep 2026).',
    ],
  },
  {
    company: 'The Nest School',
    role: 'Software Development Intern',
    place: 'Chennai, India',
    period: 'jun 2023',
    points: [
      'Solved operational problems through custom web application development.',
      'Designed and shipped websites facilitating school operations and communication.',
      'Gathered requirements directly from educators and administrative staff.',
    ],
  },
  {
    company: 'Eagle-Tech IT Solutions',
    role: 'Computer Networking Intern',
    place: 'Chennai, India',
    period: 'feb 2023',
    points: [
      'Assisted in setup and configuration of network hardware and software.',
      'Monitored network performance using Wireshark and Nagios.',
      'Documented configurations and created network diagrams.',
    ],
  },
]

export const education = [
  { school: 'Meenakshi Sundararajan Engineering College', period: '2021 — 2025', detail: 'B.Tech Information Technology · CGPA 7.85' },
  { school: 'Lalchand Milapchand Dadha Sr. Sec. School', period: '2019 — 2021', detail: 'AISSCE · Computer Science · 74.6%' },
  { school: 'Jawahar Vidyalaya', period: '2018 — 2019', detail: 'AISSE · 66%' },
]

export const achievements = [
  '/assets/images/achievements/achievement-1.webp',
  '/assets/images/achievements/achievement-2.webp',
  '/assets/images/achievements/achievement-3.webp',
  '/assets/images/achievements/achievement-4.webp',
  '/assets/images/achievements/achievement-5.webp',
  '/assets/images/achievements/achievement-6.webp',
  '/assets/images/achievements/achievement-7.webp',
  '/assets/images/achievements/achievement-8.webp',
]

export const certifications = [
  '/assets/images/certifications/certification-8.webp',
  '/assets/images/certifications/certification-1.webp',
  '/assets/images/certifications/certification-2.webp',
  '/assets/images/certifications/certification-3.webp',
  '/assets/images/certifications/certification-4.webp',
  '/assets/images/certifications/certification-5.webp',
  '/assets/images/certifications/certification-6.webp',
  '/assets/images/certifications/certification-7.webp',
]
